/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Xph4YrCiMt8
 */
import Link from "next/link"
import { CardTitle, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function IndexComponent() {
  return (
    <div className="flex flex-col min-h-screen bg-gradient-to-tl from-blue-500 via-white to-green-500 bg-wave">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link className="flex items-center justify-center" href="#">
          <img
            alt="AI for Beginners Logo"
            className="h-6 w-6"
            height="40"
            src="/placeholder.svg"
            style={{
              aspectRatio: "40/40",
              objectFit: "cover",
            }}
            width="40"
          />
          <span className="sr-only">AI for Beginners</span>
        </Link>
        <div className="mx-auto text-md font-semibold">
          Based in Grass Valley, CA, serving Nevada County, CA and surrounding areas
        </div>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Services
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            About
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Learn AI
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full pt-6 md:pt-12 lg:pt-16 border-y">
          <div className="px-4 md:px-6 space-y-10 xl:space-y-16">
            <div className="grid max-w-[1300px] mx-auto gap-4 px-4 sm:px-6 md:px-10 md:grid-cols-2 md:gap-16 items-center">
              <div>
                <h1 className="lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem]">
                  AI Can Help You
                </h1>
                <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400 mt-4 mb-4">
                  Book a coaching session to learn how to work with an AI helper, for use at home and work, and
                  transform your life.
                </p>
                <div className="space-x-4">
                  <Link
                    className="inline-flex h-9 items-center justify-center rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                    href="#"
                  >
                    Book an AI Coach Now
                  </Link>
                </div>
              </div>
              <div className="flex flex-col items-start space-y-4">
                <img
                  alt="AI Solutions"
                  className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
                  height="310"
                  src="/placeholder.svg"
                  width="550"
                />
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32" id="services">
          <div className="container space-y-12 px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800 invisible">
                  Services
                </div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Get Started Today: AI For Beginners</h2>
                <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Learn effective strategies for working with your AI buddy using natural language.
                </p>
              </div>
            </div>
            <div className="mx-auto grid items-start gap-8 sm:max-w-4xl sm:grid-cols-2 md:gap-12 lg:max-w-5xl lg:grid-cols-3">
              <Card>
                <CardHeader>
                  <CardTitle>Why Learn AI?</CardTitle>
                </CardHeader>
                <CardContent>
                  Learning to communicate your needs to AI can help you get your tasks done more efficiently, freeing up
                  your time for more important things. You deserve to be able to focus your attention on creative
                  direction, problem-solving, and decision making.
                </CardContent>
                <CardFooter>
                  <Link href="#">
                    <Button>Book Now</Button>
                  </Link>
                </CardFooter>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>One-on-One Coaching</CardTitle>
                </CardHeader>
                <CardContent>
                  Let us help you with your specific needs and focus you on what you need to know. In person, or
                  remotely, our experts will focus on you and only you.
                </CardContent>
                <CardFooter>
                  <Link href="#">
                    <Button>Book Now</Button>
                  </Link>
                </CardFooter>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>AI for Professionals</CardTitle>
                </CardHeader>
                <CardContent>
                  Transform your work life with a multifaceted AI assistant. Research, data analysis, effective
                  communication, negotiation assistance, brainstorming, visual aids, and much more.
                </CardContent>
                <CardFooter>
                  <Link href="#">
                    <Button>Book Now</Button>
                  </Link>
                </CardFooter>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>AI at Home</CardTitle>
                </CardHeader>
                <CardContent>
                  AI can help you with everything from gardening, to dating, exercise regimens, gaming, diet strategies,
                  learning languages, tutoring, and much more, tailored to you and your specific wants and needs.
                </CardContent>
                <CardFooter>
                  <Link href="#">
                    <Button>Book Now</Button>
                  </Link>
                </CardFooter>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Tailored Solutions</CardTitle>
                </CardHeader>
                <CardContent>
                  Want something more complex? Maybe you would like your AI to have a specific personality, or
                  automation of a task, or design it to help users on your website: We partner with an AI Guru to give
                  you a tailored AI to suit your purposes.
                </CardContent>
                <CardFooter>
                  <Link href="#">
                    <Button>Book Now</Button>
                  </Link>
                </CardFooter>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Imagine More</CardTitle>
                </CardHeader>
                <CardContent>
                  AI has more uses and abilities than any one person can come up with. Do you have another idea for how
                  to use it?
                </CardContent>
                <CardFooter>
                  <Link href="#">
                    <Button>Book Now</Button>
                  </Link>
                </CardFooter>
              </Card>
            </div>
          </div>
        </section>
        <section className="w-full py-4 md:py-8 lg:py-12" id="about">
          <div className="container grid items-center justify-center gap-4 px-4 md:px-6 md:grid-cols-2">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">About Me</h2>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Your AI Coach, Corey, studied Computer Science at Humboldt State University and has over a decade of
                experience in the IT industry. He is excited to be making the cutting edge technology that is Large
                Language Models accessible to everyone.
              </p>
            </div>
            <div className="flex justify-center items-center">
              <img
                alt="Expert Image"
                className="rounded-full object-cover object-center"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "200/200",
                  objectFit: "cover",
                }}
                width="200"
              />
            </div>
          </div>
        </section>
        <section className="w-full py-6 md:py-12 lg:py-18" id="contact">
          <div className="container grid items-center justify-center gap-4 px-4 md:px-6">
            <div className="space-y-1">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">Contact Us</h2>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Have any questions or want to get started? Get in touch with us.
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-x-2 flex justify-between">
              <Card>
                <CardHeader>
                  <CardTitle>Email</CardTitle>
                </CardHeader>
                <CardContent>AIFreeMyTime@gmail.com</CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Phone</CardTitle>
                </CardHeader>
                <CardContent>+1 530 277 7353</CardContent>
                <CardFooter>
                  <p className="text-gray-500">Text preferred.</p>
                </CardFooter>
              </Card>
              <Card>
                <CardContent>
                  <img
                    alt="Placeholder Image"
                    className="rounded-xl object-cover object-center mt-4"
                    height="100"
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "100/100",
                      objectFit: "cover",
                    }}
                    width="100"
                  />
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
